/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ImageRatingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialProtocolId"
      | "getEncryptedStats"
      | "getImageInfo"
      | "getTotalImages"
      | "hasRated"
      | "imageExists"
      | "submitRating"
      | "uploadImage"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ImageUploaded" | "RatingSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedStats",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getImageInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalImages",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasRated",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "imageExists",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitRating",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "uploadImage", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getImageInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalImages",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasRated", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "imageExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitRating",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uploadImage",
    data: BytesLike
  ): Result;
}

export namespace ImageUploadedEvent {
  export type InputTuple = [
    imageId: BigNumberish,
    creator: AddressLike,
    ipfsCID: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    imageId: bigint,
    creator: string,
    ipfsCID: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    imageId: bigint;
    creator: string;
    ipfsCID: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RatingSubmittedEvent {
  export type InputTuple = [
    imageId: BigNumberish,
    rater: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [imageId: bigint, rater: string, timestamp: bigint];
  export interface OutputObject {
    imageId: bigint;
    rater: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ImageRating extends BaseContract {
  connect(runner?: ContractRunner | null): ImageRating;
  waitForDeployment(): Promise<this>;

  interface: ImageRatingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getEncryptedStats: TypedContractMethod<
    [imageId: BigNumberish],
    [[string, string] & { sum: string; count: string }],
    "view"
  >;

  getImageInfo: TypedContractMethod<
    [imageId: BigNumberish],
    [
      [string, string, bigint] & {
        ipfsCID: string;
        creator: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  getTotalImages: TypedContractMethod<[], [bigint], "view">;

  hasRated: TypedContractMethod<
    [imageId: BigNumberish, rater: AddressLike],
    [boolean],
    "view"
  >;

  imageExists: TypedContractMethod<[imageId: BigNumberish], [boolean], "view">;

  submitRating: TypedContractMethod<
    [imageId: BigNumberish, encryptedRating: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  uploadImage: TypedContractMethod<[ipfsCID: string], [bigint], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEncryptedStats"
  ): TypedContractMethod<
    [imageId: BigNumberish],
    [[string, string] & { sum: string; count: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getImageInfo"
  ): TypedContractMethod<
    [imageId: BigNumberish],
    [
      [string, string, bigint] & {
        ipfsCID: string;
        creator: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalImages"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasRated"
  ): TypedContractMethod<
    [imageId: BigNumberish, rater: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "imageExists"
  ): TypedContractMethod<[imageId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "submitRating"
  ): TypedContractMethod<
    [imageId: BigNumberish, encryptedRating: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "uploadImage"
  ): TypedContractMethod<[ipfsCID: string], [bigint], "nonpayable">;

  getEvent(
    key: "ImageUploaded"
  ): TypedContractEvent<
    ImageUploadedEvent.InputTuple,
    ImageUploadedEvent.OutputTuple,
    ImageUploadedEvent.OutputObject
  >;
  getEvent(
    key: "RatingSubmitted"
  ): TypedContractEvent<
    RatingSubmittedEvent.InputTuple,
    RatingSubmittedEvent.OutputTuple,
    RatingSubmittedEvent.OutputObject
  >;

  filters: {
    "ImageUploaded(uint256,address,string,uint256)": TypedContractEvent<
      ImageUploadedEvent.InputTuple,
      ImageUploadedEvent.OutputTuple,
      ImageUploadedEvent.OutputObject
    >;
    ImageUploaded: TypedContractEvent<
      ImageUploadedEvent.InputTuple,
      ImageUploadedEvent.OutputTuple,
      ImageUploadedEvent.OutputObject
    >;

    "RatingSubmitted(uint256,address,uint256)": TypedContractEvent<
      RatingSubmittedEvent.InputTuple,
      RatingSubmittedEvent.OutputTuple,
      RatingSubmittedEvent.OutputObject
    >;
    RatingSubmitted: TypedContractEvent<
      RatingSubmittedEvent.InputTuple,
      RatingSubmittedEvent.OutputTuple,
      RatingSubmittedEvent.OutputObject
    >;
  };
}
